language: cpp # selección del lenguaje, en nuestro caso cpp.
compiler:     # compilador utilizado, en nuestro caso gcc. Pueden añadirse más de un compilador.
    - gcc     
script:       # El script que ejecutaremos para que nuestro código funcione y corra los test.
    - mkdir build && cd build
    - cmake ..
    - make
    - make test
branches:     # decidimos que TravisCI solo compruebe los test del master de github.
    only:
        - master
notifications:   # Notificamos los resultados de los test por correo
    recipients:
        - martindonofrio@gmail.com
    email:
        on_success: change
        on_failure: always
before_install:   # Instalación de dependencias
    - sudo apt-get update -qq
    - sudo apt-get install cmake libboost-all-dev libirrlicht-dev
